filebeat.inputs:
- type: httpjson
  request.url: https://try.donordrive.com/api/participants/477670/donations

  processors:
    - decode_json_fields:
        fields: ["message"]
        target: "json"

output.elasticsearch:
  hosts: ["http://es-container:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false